import logging
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)

class AttractionsService:
    def __init__(self):
        self.attractions_db = {
            "九江": [
                {"name": "庐山", "address": "九江市庐山市", "longitude": 115.96735, "latitude": 29.57345, 
                 "description": "世界文化遗产，中国著名避暑胜地，风景秀丽", "ticket_price": 160, "open_time": "06:00-20:00", 
                 "visit_duration": 360, "popularity": 5, "type": "自然景观"},
                {"name": "鄱阳湖", "address": "九江市鄱阳县", "longitude": 116.23456, "latitude": 29.01234, 
                 "description": "中国最大淡水湖，候鸟天堂", "ticket_price": 120, "open_time": "08:00-18:00", 
                 "visit_duration": 240, "popularity": 4, "type": "自然景观"},
                {"name": "浔阳楼", "address": "九江市浔阳区滨江东路908号", "longitude": 115.91342, "latitude": 29.71456, 
                 "description": "江南十大名楼之一，因《水浒传》而闻名", "ticket_price": 20, "open_time": "08:00-17:30", 
                 "visit_duration": 60, "popularity": 3, "type": "人文古迹"},
                {"name": "烟水亭", "address": "九江市浔阳区甘棠南路1号", "longitude": 115.90456, "latitude": 29.70891, 
                 "description": "建于唐代，相传为周瑜点将台", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 60, "popularity": 2, "type": "人文古迹"},
                {"name": "东林寺", "address": "九江市庐山市东林路", "longitude": 115.98765, "latitude": 29.60345, 
                 "description": "中国佛教净土宗发源地，千年古刹", "ticket_price": 0, "open_time": "08:00-17:00", 
                 "visit_duration": 90, "popularity": 3, "type": "人文古迹"},
            ],
            "杭州": [
                {"name": "西湖", "address": "杭州市西湖区", "longitude": 120.153576, "latitude": 30.287459, 
                 "description": "杭州最著名的景点，湖光山色美不胜收", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 180, "popularity": 5, "type": "自然景观"},
                {"name": "灵隐寺", "address": "杭州市西湖区灵隐路法云弄1号", "longitude": 120.141546, "latitude": 30.297985, 
                 "description": "千年古刹，香火旺盛", "ticket_price": 75, "open_time": "07:00-17:30", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "西溪湿地", "address": "杭州市西湖区天目山路518号", "longitude": 120.047227, "latitude": 30.254456, 
                 "description": "国家5A级景区，城市中的天然氧吧", "ticket_price": 80, "open_time": "07:30-18:30", 
                 "visit_duration": 240, "popularity": 4, "type": "自然景观"},
                {"name": "九溪烟树", "address": "杭州市西湖区九溪路", "longitude": 120.129744, "latitude": 30.216142, 
                 "description": "溪水潺潺，茶园叠翠，清幽宜人", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 150, "popularity": 3, "type": "自然景观"},
                {"name": "小河直街", "address": "杭州市拱墅区小河直街", "longitude": 120.155465, "latitude": 30.317571, 
                 "description": "保留完好的清末民初建筑，文艺小店云集", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 3, "type": "人文古迹"},
            ],
            "大理": [
                {"name": "洱海", "address": "大理白族自治州大理市", "longitude": 100.199898, "latitude": 25.602698, 
                 "description": "高原明珠，风光旖旎", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 240, "popularity": 5, "type": "自然景观"},
                {"name": "大理古城", "address": "大理白族自治州大理市大理古城", "longitude": 100.203643, "latitude": 25.606435, 
                 "description": "千年古城，文化底蕴深厚", "ticket_price": 35, "open_time": "全天", 
                 "visit_duration": 180, "popularity": 5, "type": "人文古迹"},
                {"name": "崇圣寺三塔", "address": "大理白族自治州大理市崇圣寺三塔文化旅游区", "longitude": 100.189991, "latitude": 25.615198, 
                 "description": "大理国时期皇家寺院，标志性建筑", "ticket_price": 75, "open_time": "07:30-19:00", 
                 "visit_duration": 120, "popularity": 4, "type": "人文古迹"},
                {"name": "喜洲古镇", "address": "大理白族自治州大理市喜洲镇", "longitude": 100.138614, "latitude": 25.683372, 
                 "description": "保存完好的白族民居建筑群", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 3, "type": "人文古迹"},
                {"name": "双廊古镇", "address": "大理白族自治州大理市双廊镇", "longitude": 100.269478, "latitude": 25.735948, 
                 "description": "洱海东岸的文艺小镇", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 150, "popularity": 4, "type": "人文古迹"},
            ],
            "上海": [
                {"name": "外滩", "address": "上海市黄浦区中山东一路", "longitude": 121.493733, "latitude": 31.230416, 
                 "description": "上海标志性景观，万国建筑博览群", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 5, "type": "现代景观"},
                {"name": "豫园", "address": "上海市黄浦区豫园老街", "longitude": 121.499748, "latitude": 31.233643, 
                 "description": "江南古典园林精品", "ticket_price": 40, "open_time": "08:30-17:30", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "陆家嘴", "address": "上海市浦东新区陆家嘴", "longitude": 121.507688, "latitude": 31.239715, 
                 "description": "中国金融中心，高楼林立", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 150, "popularity": 5, "type": "现代景观"},
                {"name": "田子坊", "address": "上海市黄浦区泰康路210弄", "longitude": 121.493076, "latitude": 31.222864, 
                 "description": "文艺青年聚集地，老上海弄堂风情", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "武康路", "address": "上海市徐汇区武康路", "longitude": 121.449428, "latitude": 31.209377, 
                 "description": "历史风貌街区，名人故居众多", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 60, "popularity": 3, "type": "人文古迹"},
            ],
            "北京": [
                {"name": "故宫", "address": "北京市东城区故宫博物院", "longitude": 116.397452, "latitude": 39.916317, 
                 "description": "世界上现存规模最大的木质结构古建筑群", "ticket_price": 60, "open_time": "08:30-17:00", 
                 "visit_duration": 300, "popularity": 5, "type": "人文古迹"},
                {"name": "颐和园", "address": "北京市海淀区颐和园", "longitude": 116.275598, "latitude": 39.999878, 
                 "description": "中国现存规模最大、保存最完整的皇家园林", "ticket_price": 30, "open_time": "06:30-20:00", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "八达岭长城", "address": "北京市延庆区八达岭镇", "longitude": 115.981925, "latitude": 40.367444, 
                 "description": "万里长城的精华段", "ticket_price": 40, "open_time": "07:30-18:00", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "南锣鼓巷", "address": "北京市东城区南锣鼓巷", "longitude": 116.403217, "latitude": 39.928759, 
                 "description": "北京最古老的街区之一", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "奥林匹克公园", "address": "北京市朝阳区奥林匹克公园", "longitude": 116.406656, "latitude": 39.996247, 
                 "description": "2008年北京奥运会举办地", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "现代景观"},
            ],
            "西安": [
                {"name": "兵马俑", "address": "西安市临潼区秦始皇兵马俑博物馆", "longitude": 109.278205, "latitude": 34.385329, 
                 "description": "世界八大奇迹之一", "ticket_price": 120, "open_time": "08:30-18:00", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "大雁塔", "address": "西安市雁塔区大慈恩寺", "longitude": 108.952024, "latitude": 34.217562, 
                 "description": "唐代佛教建筑艺术杰作", "ticket_price": 30, "open_time": "08:30-17:00", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "城墙", "address": "西安市碑林区明城墙", "longitude": 108.949234, "latitude": 34.261774, 
                 "description": "保存最完整的古城墙", "ticket_price": 54, "open_time": "08:00-22:00", 
                 "visit_duration": 180, "popularity": 4, "type": "人文古迹"},
                {"name": "永兴坊", "address": "西安市新城区永兴坊", "longitude": 108.957688, "latitude": 34.272685, 
                 "description": "陕西非遗美食文化街区", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "陕西历史博物馆", "address": "西安市雁塔区小寨东路", "longitude": 108.950563, "latitude": 34.226238, 
                 "description": "中国第一座大型现代化国家级博物馆", "ticket_price": 0, "open_time": "08:30-18:00", 
                 "visit_duration": 180, "popularity": 5, "type": "人文古迹"},
            ],
            "成都": [
                {"name": "都江堰", "address": "成都市都江堰市", "longitude": 103.619748, "latitude": 30.997825, 
                 "description": "世界文化遗产，千年水利工程", "ticket_price": 80, "open_time": "08:00-18:00", 
                 "visit_duration": 180, "popularity": 5, "type": "人文古迹"},
                {"name": "宽窄巷子", "address": "成都市青羊区宽窄巷子", "longitude": 104.063717, "latitude": 30.660719, 
                 "description": "清代古街道，成都文化地标", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 5, "type": "人文古迹"},
                {"name": "大熊猫基地", "address": "成都市成华区外北熊猫大道1375号", "longitude": 104.158378, "latitude": 30.761331, 
                 "description": "全球最大的熊猫保护研究基地", "ticket_price": 55, "open_time": "07:30-18:00", 
                 "visit_duration": 180, "popularity": 5, "type": "自然景观"},
                {"name": "锦里古街", "address": "成都市武侯区武侯祠大街231号", "longitude": 104.043434, "latitude": 30.646963, 
                 "description": "古蜀文化商业街，美食聚集地", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "人文古迹"},
                {"name": "杜甫草堂", "address": "成都市青羊区青华路37号", "longitude": 104.032345, "latitude": 30.655757, 
                 "description": "唐代诗人杜甫故居", "ticket_price": 50, "open_time": "08:30-18:30", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "重庆": [
                {"name": "洪崖洞", "address": "重庆市渝中区嘉陵江滨江路88号", "longitude": 106.587139, "latitude": 29.431574, 
                 "description": "巴渝传统吊脚楼建筑群", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "长江索道", "address": "重庆市渝中区新华路151号", "longitude": 106.584678, "latitude": 29.421117, 
                 "description": "横跨长江的空中交通", "ticket_price": 20, "open_time": "07:30-22:30", 
                 "visit_duration": 30, "popularity": 4, "type": "现代景观"},
                {"name": "磁器口古镇", "address": "重庆市沙坪坝区磁器口古镇", "longitude": 106.453691, "latitude": 29.499169, 
                 "description": "千年古镇，重庆缩影", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 150, "popularity": 4, "type": "人文古迹"},
                {"name": "解放碑", "address": "重庆市渝中区解放碑步行街", "longitude": 106.588368, "latitude": 29.432846, 
                 "description": "重庆地标，商业中心", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 60, "popularity": 5, "type": "现代景观"},
                {"name": "李子坝轻轨站", "address": "重庆市渝中区李子坝", "longitude": 106.566513, "latitude": 29.436545, 
                 "description": "穿楼而过的轻轨，网红打卡点", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 30, "popularity": 4, "type": "现代景观"},
            ],
            "广州": [
                {"name": "广州塔", "address": "广州市海珠区阅江西路222号", "longitude": 113.330443, "latitude": 23.113552, 
                 "description": "广州新地标，小蛮腰", "ticket_price": 150, "open_time": "09:30-22:30", 
                 "visit_duration": 120, "popularity": 5, "type": "现代景观"},
                {"name": "陈家祠", "address": "广州市荔湾区中山七路恩龙里34号", "longitude": 113.257348, "latitude": 23.133412, 
                 "description": "岭南建筑艺术明珠", "ticket_price": 10, "open_time": "08:30-17:30", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "沙面岛", "address": "广州市荔湾区沙面岛", "longitude": 113.239488, "latitude": 23.125719, 
                 "description": "欧陆风情小岛，历史建筑群", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "白云山", "address": "广州市白云区广园中路801号", "longitude": 113.216404, "latitude": 23.191482, 
                 "description": "南粤名山，羊城第一秀", "ticket_price": 5, "open_time": "06:00-22:00", 
                 "visit_duration": 240, "popularity": 4, "type": "自然景观"},
                {"name": "北京路步行街", "address": "广州市越秀区北京路", "longitude": 113.262428, "latitude": 23.125818, 
                 "description": "千年商业老街", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "深圳": [
                {"name": "世界之窗", "address": "深圳市南山区深南大道9037号", "longitude": 113.975198, "latitude": 22.542858, 
                 "description": "微缩世界景观主题公园", "ticket_price": 220, "open_time": "09:00-22:30", 
                 "visit_duration": 300, "popularity": 5, "type": "现代景观"},
                {"name": "东部华侨城", "address": "深圳市盐田区大梅沙东部华侨城", "longitude": 114.310172, "latitude": 22.583475, 
                 "description": "大型综合性旅游度假区", "ticket_price": 200, "open_time": "09:30-18:00", 
                 "visit_duration": 300, "popularity": 4, "type": "现代景观"},
                {"name": "莲花山公园", "address": "深圳市福田区红荔路6030号", "longitude": 114.056304, "latitude": 22.549928, 
                 "description": "城市中心绿肺，邓小平铜像", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "自然景观"},
                {"name": "大鹏古城", "address": "深圳市大鹏新区大鹏街道", "longitude": 114.379783, "latitude": 22.606847, 
                 "description": "深圳历史最悠久的古城", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 3, "type": "人文古迹"},
                {"name": "欢乐海岸", "address": "深圳市南山区白石路东8号", "longitude": 113.964704, "latitude": 22.537669, 
                 "description": "都市娱乐目的地", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "现代景观"},
            ],
            "成都": [
                {"name": "都江堰", "address": "成都市都江堰市", "longitude": 103.619748, "latitude": 30.997825, 
                 "description": "世界文化遗产，千年水利工程", "ticket_price": 80, "open_time": "08:00-18:00", 
                 "visit_duration": 180, "popularity": 5, "type": "人文古迹"},
                {"name": "宽窄巷子", "address": "成都市青羊区宽窄巷子", "longitude": 104.063717, "latitude": 30.660719, 
                 "description": "清代古街道，成都文化地标", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 5, "type": "人文古迹"},
                {"name": "大熊猫基地", "address": "成都市成华区外北熊猫大道1375号", "longitude": 104.158378, "latitude": 30.761331, 
                 "description": "全球最大的熊猫保护研究基地", "ticket_price": 55, "open_time": "07:30-18:00", 
                 "visit_duration": 180, "popularity": 5, "type": "自然景观"},
                {"name": "锦里古街", "address": "成都市武侯区武侯祠大街231号", "longitude": 104.043434, "latitude": 30.646963, 
                 "description": "古蜀文化商业街，美食聚集地", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "人文古迹"},
                {"name": "杜甫草堂", "address": "成都市青羊区青华路37号", "longitude": 104.032345, "latitude": 30.655757, 
                 "description": "唐代诗人杜甫故居", "ticket_price": 50, "open_time": "08:30-18:30", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "苏州": [
                {"name": "拙政园", "address": "苏州市姑苏区东北街178号", "longitude": 120.623722, "latitude": 31.320069, 
                 "description": "中国四大名园之首", "ticket_price": 80, "open_time": "07:30-17:00", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "平江路", "address": "苏州市姑苏区平江路", "longitude": 120.625664, "latitude": 31.323348, 
                 "description": "苏州古城风貌街区", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "寒山寺", "address": "苏州市姑苏区枫桥路", "longitude": 120.586411, "latitude": 31.320452, 
                 "description": "因唐诗《枫桥夜泊》闻名", "ticket_price": 20, "open_time": "07:30-17:00", 
                 "visit_duration": 60, "popularity": 4, "type": "人文古迹"},
                {"name": "周庄古镇", "address": "苏州市昆山市周庄镇", "longitude": 120.892717, "latitude": 31.073884, 
                 "description": "江南水乡代表", "ticket_price": 100, "open_time": "08:00-21:00", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "狮子林", "address": "苏州市姑苏区园林路23号", "longitude": 120.626755, "latitude": 31.316354, 
                 "description": "以假山闻名的古典园林", "ticket_price": 40, "open_time": "07:30-17:00", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "南京": [
                {"name": "中山陵", "address": "南京市玄武区中山门外", "longitude": 118.806524, "latitude": 32.061243, 
                 "description": "孙中山先生陵墓", "ticket_price": 0, "open_time": "08:30-17:00", 
                 "visit_duration": 150, "popularity": 5, "type": "人文古迹"},
                {"name": "夫子庙", "address": "南京市秦淮区夫子庙", "longitude": 118.796973, "latitude": 32.039625, 
                 "description": "中国四大文庙之一", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "明孝陵", "address": "南京市玄武区钟山风景名胜区", "longitude": 118.811768, "latitude": 32.048973, 
                 "description": "明太祖朱元璋陵墓", "ticket_price": 70, "open_time": "06:30-18:30", 
                 "visit_duration": 180, "popularity": 4, "type": "人文古迹"},
                {"name": "秦淮河", "address": "南京市秦淮区秦淮河", "longitude": 118.797935, "latitude": 32.038626, 
                 "description": "南京母亲河，夜游胜地", "ticket_price": 60, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "自然景观"},
                {"name": "老门东", "address": "南京市秦淮区老门东", "longitude": 118.801341, "latitude": 32.034274, 
                 "description": "老南京文化街区", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "武汉": [
                {"name": "黄鹤楼", "address": "武汉市武昌区蛇山西山坡特1号", "longitude": 114.306555, "latitude": 30.543495, 
                 "description": "江南三大名楼之一", "ticket_price": 80, "open_time": "08:30-17:00", 
                 "visit_duration": 90, "popularity": 5, "type": "人文古迹"},
                {"name": "东湖", "address": "武汉市武昌区东湖生态旅游风景区", "longitude": 114.360292, "latitude": 30.547635, 
                 "description": "中国最大的城中湖", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 180, "popularity": 5, "type": "自然景观"},
                {"name": "户部巷", "address": "武汉市武昌区户部巷", "longitude": 114.301802, "latitude": 30.540698, 
                 "description": "武汉美食一条街", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "湖北省博物馆", "address": "武汉市武昌区东湖路156号", "longitude": 114.350307, "latitude": 30.554568, 
                 "description": "国家一级博物馆", "ticket_price": 0, "open_time": "09:00-17:00", 
                 "visit_duration": 180, "popularity": 5, "type": "人文古迹"},
                {"name": "昙华林", "address": "武汉市武昌区昙华林", "longitude": 114.308236, "latitude": 30.549173, 
                 "description": "文艺青年聚集地", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 3, "type": "人文古迹"},
            ],
            "青岛": [
                {"name": "崂山", "address": "青岛市崂山区", "longitude": 120.665665, "latitude": 36.144631, 
                 "description": "海上第一名山", "ticket_price": 120, "open_time": "06:00-18:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "八大关", "address": "青岛市市南区八大关", "longitude": 120.330579, "latitude": 36.058671, 
                 "description": "万国建筑博览区", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "栈桥", "address": "青岛市市南区太平路", "longitude": 120.314703, "latitude": 36.064377, 
                 "description": "青岛城市标志", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 60, "popularity": 5, "type": "现代景观"},
                {"name": "五四广场", "address": "青岛市市南区东海西路", "longitude": 120.339612, "latitude": 36.055626, 
                 "description": "青岛地标，五月的风雕塑", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 60, "popularity": 4, "type": "现代景观"},
                {"name": "石老人浴场", "address": "青岛市崂山区石老人浴场", "longitude": 120.437451, "latitude": 36.057202, 
                 "description": "天然海水浴场", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "自然景观"},
            ],
            "厦门": [
                {"name": "鼓浪屿", "address": "厦门市思明区鼓浪屿", "longitude": 118.089185, "latitude": 24.467662, 
                 "description": "世界文化遗产，海上花园", "ticket_price": 35, "open_time": "全天", 
                 "visit_duration": 240, "popularity": 5, "type": "自然景观"},
                {"name": "厦门大学", "address": "厦门市思明区思明南路422号", "longitude": 118.085199, "latitude": 24.463427, 
                 "description": "中国最美大学之一", "ticket_price": 0, "open_time": "12:00-14:00", 
                 "visit_duration": 120, "popularity": 5, "type": "现代景观"},
                {"name": "南普陀寺", "address": "厦门市思明区思明南路515号", "longitude": 118.082698, "latitude": 24.459998, 
                 "description": "闽南著名古刹", "ticket_price": 0, "open_time": "08:00-17:30", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "曾厝垵", "address": "厦门市思明区曾厝垵", "longitude": 118.120709, "latitude": 24.451719, 
                 "description": "文艺渔村，美食街", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
                {"name": "环岛路", "address": "厦门市思明区环岛路", "longitude": 118.107433, "latitude": 24.441341, 
                 "description": "滨海风光大道", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "自然景观"},
            ],
            "三亚": [
                {"name": "亚龙湾", "address": "三亚市吉阳区亚龙湾", "longitude": 109.534419, "latitude": 18.202612, 
                 "description": "天下第一湾", "ticket_price": 80, "open_time": "全天", 
                 "visit_duration": 180, "popularity": 5, "type": "自然景观"},
                {"name": "天涯海角", "address": "三亚市天涯区天涯海角", "longitude": 109.204435, "latitude": 18.212651, 
                 "description": "三亚标志性景点", "ticket_price": 81, "open_time": "08:00-18:00", 
                 "visit_duration": 150, "popularity": 5, "type": "自然景观"},
                {"name": "蜈支洲岛", "address": "三亚市海棠区蜈支洲岛", "longitude": 109.662636, "latitude": 18.347338, 
                 "description": "中国马尔代夫", "ticket_price": 144, "open_time": "08:00-18:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "南山文化旅游区", "address": "三亚市崖州区南山", "longitude": 108.975778, "latitude": 18.246334, 
                 "description": "108米高的海上观音", "ticket_price": 129, "open_time": "08:00-17:30", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "大东海", "address": "三亚市吉阳区大东海", "longitude": 109.511617, "latitude": 18.252497, 
                 "description": "三亚最早开发的海滨浴场", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "自然景观"},
            ],
            "桂林": [
                {"name": "漓江", "address": "桂林市阳朔县漓江", "longitude": 110.475169, "latitude": 24.812541, 
                 "description": "山水甲天下", "ticket_price": 215, "open_time": "08:00-17:00", 
                 "visit_duration": 360, "popularity": 5, "type": "自然景观"},
                {"name": "阳朔西街", "address": "桂林市阳朔县阳朔西街", "longitude": 110.464756, "latitude": 24.779649, 
                 "description": "阳朔最热闹的商业街", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "象鼻山", "address": "桂林市象山区象鼻山", "longitude": 110.299572, "latitude": 25.275093, 
                 "description": "桂林城徽", "ticket_price": 55, "open_time": "08:00-17:30", 
                 "visit_duration": 90, "popularity": 5, "type": "自然景观"},
                {"name": "遇龙河", "address": "桂林市阳朔县遇龙河", "longitude": 110.461078, "latitude": 24.835797, 
                 "description": "小漓江，竹筏漂流", "ticket_price": 160, "open_time": "08:00-17:00", 
                 "visit_duration": 180, "popularity": 4, "type": "自然景观"},
                {"name": "兴坪古镇", "address": "桂林市阳朔县兴坪古镇", "longitude": 110.535237, "latitude": 24.848337, 
                 "description": "漓江边上的千年古镇", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 4, "type": "人文古迹"},
            ],
            "丽江": [
                {"name": "丽江古城", "address": "丽江市古城区丽江古城", "longitude": 100.236461, "latitude": 26.864114, 
                 "description": "世界文化遗产，茶马古道重镇", "ticket_price": 80, "open_time": "全天", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "玉龙雪山", "address": "丽江市玉龙纳西族自治县玉龙雪山", "longitude": 100.221109, "latitude": 27.038985, 
                 "description": "北半球最南端的雪山", "ticket_price": 100, "open_time": "07:30-16:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "束河古镇", "address": "丽江市古城区束河古镇", "longitude": 100.207013, "latitude": 26.875372, 
                 "description": "比丽江古城更安静的古镇", "ticket_price": 40, "open_time": "全天", 
                 "visit_duration": 150, "popularity": 4, "type": "人文古迹"},
                {"name": "黑龙潭", "address": "丽江市古城区黑龙潭", "longitude": 100.233416, "latitude": 26.880792, 
                 "description": "丽江古城的水源地", "ticket_price": 0, "open_time": "07:30-17:30", 
                 "visit_duration": 90, "popularity": 4, "type": "自然景观"},
                {"name": "拉市海", "address": "丽江市玉龙纳西族自治县拉市海", "longitude": 100.164678, "latitude": 26.836383, 
                 "description": "高原湿地，茶马古道体验", "ticket_price": 60, "open_time": "08:00-18:00", 
                 "visit_duration": 180, "popularity": 4, "type": "自然景观"},
            ],
            "张家界": [
                {"name": "张家界国家森林公园", "address": "张家界市武陵源区张家界国家森林公园", "longitude": 110.473527, "latitude": 29.295721, 
                 "description": "世界自然遗产，阿凡达取景地", "ticket_price": 225, "open_time": "07:30-18:00", 
                 "visit_duration": 480, "popularity": 5, "type": "自然景观"},
                {"name": "天门山", "address": "张家界市永定区天门山", "longitude": 110.481415, "latitude": 29.160513, 
                 "description": "天门洞奇观", "ticket_price": 278, "open_time": "08:00-17:30", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "黄龙洞", "address": "张家界市武陵源区黄龙洞", "longitude": 110.526835, "latitude": 29.316081, 
                 "description": "中国最美的溶洞", "ticket_price": 100, "open_time": "08:00-17:30", 
                 "visit_duration": 120, "popularity": 4, "type": "自然景观"},
                {"name": "大峡谷玻璃桥", "address": "张家界市慈利县张家界大峡谷", "longitude": 110.681275, "latitude": 29.239149, 
                 "description": "世界最高最长的玻璃桥", "ticket_price": 259, "open_time": "08:00-17:00", 
                 "visit_duration": 180, "popularity": 5, "type": "现代景观"},
                {"name": "凤凰古城", "address": "湘西土家族苗族自治州凤凰县", "longitude": 109.426537, "latitude": 27.940906, 
                 "description": "湘西明珠，沈从文笔下的边城", "ticket_price": 148, "open_time": "全天", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
            ],
            "九寨沟": [
                {"name": "九寨沟", "address": "阿坝藏族羌族自治州九寨沟县", "longitude": 103.908139, "latitude": 33.235966, 
                 "description": "世界自然遗产，人间仙境", "ticket_price": 190, "open_time": "08:30-17:00", 
                 "visit_duration": 480, "popularity": 5, "type": "自然景观"},
                {"name": "黄龙", "address": "阿坝藏族羌族自治州松潘县", "longitude": 103.824259, "latitude": 32.616311, 
                 "description": "世界自然遗产，钙华彩池", "ticket_price": 170, "open_time": "08:00-17:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "牟尼沟", "address": "阿坝藏族羌族自治州松潘县", "longitude": 103.781331, "latitude": 32.741786, 
                 "description": "小巧玲珑的人间仙境", "ticket_price": 100, "open_time": "08:00-17:00", 
                 "visit_duration": 240, "popularity": 3, "type": "自然景观"},
            ],
            "香格里拉": [
                {"name": "普达措国家公园", "address": "迪庆藏族自治州香格里拉市", "longitude": 99.923358, "latitude": 27.825633, 
                 "description": "高原生态旅游区", "ticket_price": 138, "open_time": "08:00-17:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "独克宗古城", "address": "迪庆藏族自治州香格里拉市", "longitude": 99.722554, "latitude": 27.849087, 
                 "description": "茶马古道重镇", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 120, "popularity": 4, "type": "人文古迹"},
                {"name": "松赞林寺", "address": "迪庆藏族自治州香格里拉市", "longitude": 99.730198, "latitude": 27.865129, 
                 "description": "小布达拉宫", "ticket_price": 115, "open_time": "07:30-19:00", 
                 "visit_duration": 150, "popularity": 5, "type": "人文古迹"},
                {"name": "纳帕海", "address": "迪庆藏族自治州香格里拉市", "longitude": 99.677415, "latitude": 27.859939, 
                 "description": "高原季节性湖泊", "ticket_price": 60, "open_time": "08:00-18:00", 
                 "visit_duration": 150, "popularity": 4, "type": "自然景观"},
            ],
            "拉萨": [
                {"name": "布达拉宫", "address": "拉萨市城关区北京中路", "longitude": 91.133151, "latitude": 29.654021, 
                 "description": "世界屋脊上的明珠", "ticket_price": 200, "open_time": "09:00-16:00", 
                 "visit_duration": 240, "popularity": 5, "type": "人文古迹"},
                {"name": "大昭寺", "address": "拉萨市城关区八廓街", "longitude": 91.138965, "latitude": 29.658761, 
                 "description": "藏传佛教圣地", "ticket_price": 85, "open_time": "08:30-18:30", 
                 "visit_duration": 120, "popularity": 5, "type": "人文古迹"},
                {"name": "八廓街", "address": "拉萨市城关区八廓街", "longitude": 91.137596, "latitude": 29.658033, 
                 "description": "拉萨最古老的街道", "ticket_price": 0, "open_time": "全天", 
                 "visit_duration": 90, "popularity": 5, "type": "人文古迹"},
                {"name": "纳木错", "address": "那曲市当雄县纳木错", "longitude": 90.664376, "latitude": 30.778349, 
                 "description": "西藏三大圣湖之一", "ticket_price": 120, "open_time": "06:00-18:00", 
                 "visit_duration": 300, "popularity": 5, "type": "自然景观"},
                {"name": "羊卓雍措", "address": "山南市浪卡子县羊卓雍措", "longitude": 90.568718, "latitude": 29.060124, 
                 "description": "西藏三大圣湖之一", "ticket_price": 60, "open_time": "08:00-18:00", 
                 "visit_duration": 240, "popularity": 5, "type": "自然景观"},
            ],
        }
    
    def get_attractions(self, city: str, avoid_crowds: bool = False) -> List[Dict[str, Any]]:
        try:
            logger.info(f"Getting attractions for {city}, avoid_crowds={avoid_crowds}")
            
            attractions = self.attractions_db.get(city, [])
            
            if avoid_crowds:
                attractions = [a for a in attractions if a.get("popularity", 5) <= 3]
            else:
                attractions = sorted(attractions, key=lambda x: x.get("popularity", 0), reverse=True)
            
            return attractions
            
        except Exception as e:
            logger.error(f"Failed to get attractions: {e}")
            return []
    
    def get_attraction_detail(self, city: str, name: str) -> Optional[Dict[str, Any]]:
        try:
            attractions = self.attractions_db.get(city, [])
            for attr in attractions:
                if attr.get("name") == name:
                    return attr
            return None
        except Exception as e:
            logger.error(f"Failed to get attraction detail: {e}")
            return None